# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.0.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.0.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/sre/data/Projects/me/cheminot.c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/sre/data/Projects/me/cheminot.c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/2.8.12.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.0.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.0.2/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sre/data/Projects/me/cheminot.c/CMakeFiles /Users/sre/data/Projects/me/cheminot.c/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sre/data/Projects/me/cheminot.c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cheminotc

# Build rule for target.
cheminotc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cheminotc
.PHONY : cheminotc

# fast build rule for target.
cheminotc/fast:
	$(MAKE) -f CMakeFiles/cheminotc.dir/build.make CMakeFiles/cheminotc.dir/build
.PHONY : cheminotc/fast

#=============================================================================
# Target rules for targets named cheminotc_units

# Build rule for target.
cheminotc_units: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cheminotc_units
.PHONY : cheminotc_units

# fast build rule for target.
cheminotc_units/fast:
	$(MAKE) -f CMakeFiles/cheminotc_units.dir/build.make CMakeFiles/cheminotc_units.dir/build
.PHONY : cheminotc_units/fast

#=============================================================================
# Target rules for targets named runUnitTests

# Build rule for target.
runUnitTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runUnitTests
.PHONY : runUnitTests

# fast build rule for target.
runUnitTests/fast:
	$(MAKE) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/build
.PHONY : runUnitTests/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f lib/gtest-1.7.0/CMakeFiles/gtest.dir/build.make lib/gtest-1.7.0/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f lib/gtest-1.7.0/CMakeFiles/gtest_main.dir/build.make lib/gtest-1.7.0/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

cheminotc.o: cheminotc.cpp.o
.PHONY : cheminotc.o

# target to build an object file
cheminotc.cpp.o:
	$(MAKE) -f CMakeFiles/cheminotc.dir/build.make CMakeFiles/cheminotc.dir/cheminotc.cpp.o
.PHONY : cheminotc.cpp.o

cheminotc.i: cheminotc.cpp.i
.PHONY : cheminotc.i

# target to preprocess a source file
cheminotc.cpp.i:
	$(MAKE) -f CMakeFiles/cheminotc.dir/build.make CMakeFiles/cheminotc.dir/cheminotc.cpp.i
.PHONY : cheminotc.cpp.i

cheminotc.s: cheminotc.cpp.s
.PHONY : cheminotc.s

# target to generate assembly for a file
cheminotc.cpp.s:
	$(MAKE) -f CMakeFiles/cheminotc.dir/build.make CMakeFiles/cheminotc.dir/cheminotc.cpp.s
.PHONY : cheminotc.cpp.s

tests/cheminotc.o: tests/cheminotc.cpp.o
.PHONY : tests/cheminotc.o

# target to build an object file
tests/cheminotc.cpp.o:
	$(MAKE) -f CMakeFiles/cheminotc_units.dir/build.make CMakeFiles/cheminotc_units.dir/tests/cheminotc.cpp.o
	$(MAKE) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/tests/cheminotc.cpp.o
.PHONY : tests/cheminotc.cpp.o

tests/cheminotc.i: tests/cheminotc.cpp.i
.PHONY : tests/cheminotc.i

# target to preprocess a source file
tests/cheminotc.cpp.i:
	$(MAKE) -f CMakeFiles/cheminotc_units.dir/build.make CMakeFiles/cheminotc_units.dir/tests/cheminotc.cpp.i
	$(MAKE) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/tests/cheminotc.cpp.i
.PHONY : tests/cheminotc.cpp.i

tests/cheminotc.s: tests/cheminotc.cpp.s
.PHONY : tests/cheminotc.s

# target to generate assembly for a file
tests/cheminotc.cpp.s:
	$(MAKE) -f CMakeFiles/cheminotc_units.dir/build.make CMakeFiles/cheminotc_units.dir/tests/cheminotc.cpp.s
	$(MAKE) -f CMakeFiles/runUnitTests.dir/build.make CMakeFiles/runUnitTests.dir/tests/cheminotc.cpp.s
.PHONY : tests/cheminotc.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... cheminotc"
	@echo "... cheminotc_units"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... runUnitTests"
	@echo "... test"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... cheminotc.o"
	@echo "... cheminotc.i"
	@echo "... cheminotc.s"
	@echo "... tests/cheminotc.o"
	@echo "... tests/cheminotc.i"
	@echo "... tests/cheminotc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

